### ISSUE TITLE
🐛 command not found in macos

### ISSUE THREAD

**Issue by vecpeng** [gofiber/cli#89]
**Issue description**
I run ` go get -u github.com/gofiber/cli/fiber`, and then use `fiber dev` in the zsh,  but get the error "zsh: command not found: fiber".
How can I fix it?
Environment: macOS Monterey 12.1, go version go1.17.4 darwin/amd64.

**Comment by ReneWerner87** [comment]
what was your solution ?@vecpeng

**Comment by SabryTarek** [comment]
> what was your solution ?@vecpeng

I have the same issue, any suggestions?

**Comment by sappsdev** [comment]
`nano ~/.profile`

and add this lines

`
PATH="/usr/local/bin/go/bin:$PATH"
GOPATH=$HOME/go
GOROOT=/usr/local/go
PATH="$HOME/go/bin:$PATH"
PATH="$GOPATH/bin:$PATH"
`

save and 

`source ~/.profile`

**Comment by mbecker** [comment]
Hi,

my GOPATH and GOROOT are set correctly. Because of the go mod package system the "go get -u" does not work inside a go module as explained at the following link: [https://stackoverflow.com/a/68559728](https://stackoverflow.com/a/68559728)

The following installation command did the trick:
```sh
go install github.com/gofiber/cli/fiber@latest
```

Hope this helps!
